setup_arguments:
  - name: Branch
    short: -b
    long: --branch
    description: Select which branch of kohya to check out on new installs.
    default: master
  - name: Dir
    short: -d
    long: --dir
    description: The full path you want kohya_ss installed to.
    default: ~/kohya_ss
  - name: File
    short: -f
    long: --file
    description: Path to the configuration file.
    default: ./config_files/installation/install_config.yaml
  - name: GitRepo
    short: -g
    long: --gitrepo
    description: You can optionally provide a git repo to check out for runpod installation. Useful for custom forks.
    default: https://github.com/kohya/kohya_ss.git
  - name: Interactive
    short: -i
    long: --interactive
    description: Interactively configure accelerate instead of using default config file.
    default: false
  - name: NoGitUpdate
    short: -n
    long: --nogitupdate
    description: Do not update kohya_ss repo. No git pull or clone operations.
    default: false
  - name: Public
    short: -p
    long: --public
    description: Expose public URL in runpod mode. Won't have an effect in other modes.
    default: false
  - name: Runpod
    short: -r
    long: --runpod
    description: Forces a runpod installation. Useful if detection fails for any reason.
    default: false
  - name: SkipSpaceCheck
    short: -s
    long: --skipspacecheck
    description: Skip the 10Gb minimum storage space check.
    default: false
  - name: Verbose
    short: -v
    long: --verbose
    description: Increase verbosity levels up to 3.
    default: 0
  - name: SkipSetup
    short: -x
    long: --exclude-setup
    description: Skip all setup steps and only validate python requirements then launch GUI.
    default: false

kohya_gui_arguments:
  - name: GuiListen
    short: --gui-listen
    long: --gui-listen
    description: IP to listen on for connections to Gradio.
    default: 127.0.0.1
  - name: GuiUsername
    short: --gui-username
    long: --gui-username
    description: Username for authentication.
    default: ''
  - name: GuiPassword
    short: --gui-password
    long: --gui-password
    description: Password for authentication.
    default: ''
  - name: GuiServerPort
    short: --gui-server-port
    long: --gui-server-port
    description: Port to run the server listener on.
    default: 0
  - name: GuiInbrowser
    short: --gui-inbrowser
    long: --gui-inbrowser
    description: Open in browser.
    default: false
  - name: GuiShare
    short: --gui-share
    long: --gui-share
    description: Share the gradio UI.
    default: false
