setup_arguments:
  - name: Branch
    description: Select which branch of kohya to check out on new installs.
    value: master
  - name: Dir
    description: The full path you want kohya_ss installed to.
    value: _CURRENT_SCRIPT_DIR_
  - name: GitRepo
    description: You can optionally provide a git repo to check out. Useful for custom forks.
    value: https://github.com/bmaltais/kohya_ss.git
  - name: Interactive
    description: Interactively configure accelerate instead of using value config file.
    value: false
  - name: LogDir
    description: Override the default log directory.
    value: ''
  - name: NoSetup
    description: Skip all setup steps and only validate python requirements then launch GUI.
    value: false
  - name: Public
    description: Expose public URL in runpod mode. Won't have an effect in other modes.
    value: false
  - name: Repair
    description: This runs the installation repair operations. These could take a few minutes to run.
    value: false
  - name: Runpod
    description: Forces a runpod installation. Useful if detection fails for any reason.
    value: false
  - name: SkipSpaceCheck
    description: Skip the 10Gb minimum storage space check.
    value: false
  - name: Update
    description: Update kohya_ss with specified branch, repo, or latest stable if git's unavailable.
    value: false
  - name: Verbosity
    description: Increase verbosity levels up to 3.
    value: 0

kohya_gui_arguments:
  - name: Inbrowser
    description: Open in browser.
    value: false
  - name: Listen
    description: IP to listen on for connections to Gradio.
    value: 127.0.0.1
  - name: Password
    description: Password for authentication.
    value: ''
  - name: ServerPort
    description: Port to run the server listener on.
    value: 7861
  - name: Share
    description: Share the gradio UI.
    value: false
  - name: Username
    description: Username for authentication.
    value:
